# Generated by Django 2.1.7 on 2019-02-27 11:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=10, verbose_name='性別')),
                ('age', models.IntegerField(verbose_name='年齢')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lessonname', models.CharField(max_length=100, verbose_name='ジャンル')),
                ('basicCharge', models.IntegerField(verbose_name='基本料金')),
                ('includeHour', models.IntegerField(verbose_name='インクルージョン時間')),
                ('hourlyRate', models.CharField(max_length=150, verbose_name='従量料金')),
            ],
        ),
        migrations.CreateModel(
            name='LessonHistory',
            fields=[
                ('lessonhistory_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lessonDate', models.DateField(default=django.utils.timezone.now, verbose_name='受講日')),
                ('lessonHours', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='受講時間')),
                ('customerName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessonmgmt.Customer', verbose_name='顧客名')),
                ('lessonName', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessonmgmt.Lesson', verbose_name='講座名')),
            ],
        ),
    ]
