# Generated by Django 2.1.7 on 2019-03-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonmgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lessonname',
            new_name='lessonName',
        ),
    ]
